version: '2'
services:
  app:
    build: .
    env_file: .env
    command: ./entrypoint_webapp.sh
    ports:
      - 5000:5000
    volumes:
      - .:/myapp
    depends_on:
      - mongodb
      - redis

  sidekiq:
    build: .
    env_file: .env
    command: ./entrypoint_sidekiq.sh
    volumes:
      - .:/myapp
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./rundata/redis:/data

  mongodb:
    image: mongo:latest
    volumes:
      - ./rundata/mongodb:/data/db
 